### PR TITLE
Cleanup: IOCTL functions for kvm command codes

### PR DESCRIPTION
**Pull request by ChriMarMe**
Change arbitrary command codes into proper IOCTL functions for better readability.

Signed-off-by: Christopher Meis <christopher.meis@9elements.com>

### CODE REVIEW

**Comment by ChriMarMe** [comment]
How to proceed? The old implementation wasn't good for readability and extensibility, this one is not good because "globals", which are not really global.

**Comment by bobuhiro11** [comment]
Thanks for your pull request!
I have no knowledge of how these magic numbers are calculated, so this is a great modification.
If you are going to make such a modification, I think you should unit test it to make sure it produces exactly the same value as the existing one.
For example, `IIO(kvmGetAPIVersion)` and 44544 are identical.

**Comment by ChriMarMe** [comment]
IOCTL calls are some kind of magic indeed. Half the implementation was there already, just wasn't used. 
Now it is! :) 

I will add unit tests asap.

**Comment by ChriMarMe** [comment]
Ok, that's odd.

```
loading .bashrc finished.

defaultsh-5.0# --- FAIL: TestHalt (0.02s)

    machine_test.go:104: Open: got bad file descriptor, want nil

FAIL
```
That's odd......

**Comment by ChriMarMe** [comment]
```
defaultsh-5.0# --- FAIL: TestSetupGetSetRegs (0.01s)

    machine_test.go:239: Open: got failed GetVCPUMMapSizebad file descriptor, want nil

FAIL
```

I don't know what's happening. Errors seem non-deterministic.

**Comment by ChriMarMe** [comment]
Any idea why the ci breaks welcome. I have no clue.

**Comment by bobuhiro11** [comment]
I did a quick test.
The value of KvmIRQLine seems to be different from the master branch, is this correct?

```bash
ubuntu2004thinkpad:~/gokvm$ git --no-pager diff
diff --git a/kvm/kvm_test.go b/kvm/kvm_test.go
index b54de94faa92..72da4f8f46aa 100644
--- a/kvm/kvm_test.go
+++ b/kvm/kvm_test.go
@@ -404,3 +404,73 @@ func TestIoctlStringer(t *testing.T) {
                })
        }
 }
+
+const (
+       kvmGetAPIVersion     = 0x00
+       kvmCreateVM          = 0x1
+       kvmGetVCPUMMapSize   = 0x04
+       kvmGetSupportedCPUID = 0x05
+
+       kvmCreateVCPU          = 0x41
+       kvmSetUserMemoryRegion = 0x46
+       kvmSetTSSAddr          = 0x47
+       kvmSetIdentityMapAddr  = 0x48
+
+       kvmCreateIRQChip = 0x60
+       kvmIRQLine       = 0x61
+       kvmCreatePIT2    = 0x77
+
+       kvmRun      = 0x80
+       kvmGetRegs  = 0x81
+       kvmSetRegs  = 0x82
+       kvmGetSregs = 0x83
+       kvmSetSregs = 0x84
+
+       kvmSetCPUID2 = 0x90
+)
+type irqLevel struct {
+       IRQ   uint32
+       Level uint32
+}
+
+type pitConfig struct {
+       Flags uint32
+       _     [15]uint32
+}
+
+func TestConst(t *testing.T) {
+       t.Parallel()
+
+       var kvmCPUID *kvm.CPUID
+
+       for _, test := range []struct {
+               name string
+               got  uintptr
+               want uintptr
+       }{
+               {name:"kvmGetAPIVersion"       , got: kvm.IIO(kvmGetAPIVersion), want: 44544},
+               {name:"kvmCreateVM"            , got: kvm.IIO(kvmCreateVM), want: 44545},
+               {name:"kvmCreateVCPU"          , got: kvm.IIO(kvmCreateVCPU), want: 44609},
+               {name:"kvmRun"                 , got: kvm.IIO(kvmRun), want: 44672},
+               {name:"kvmGetVCPUMMapSize"     , got: kvm.IIO(kvmGetVCPUMMapSize), want: 44548},
+               {name:"kvmGetSregs"            , got: kvm.IIOR(kvmGetSregs, unsafe.Sizeof(kvm.Sregs{})), want: 0x8138ae83},
+               {name:"kvmSetSregs"            , got: kvm.IIOW(kvmSetSregs, unsafe.Sizeof(kvm.Sregs{})), want: 0x4138ae84},
+               {name:"kvmGetRegs"             , got: kvm.IIOR(kvmGetRegs, unsafe.Sizeof(kvm.Regs{})), want: 0x8090ae81},
+               {name:"kvmSetRegs"             , got: kvm.IIOW(kvmSetRegs, unsafe.Sizeof(kvm.Regs{})), want: 0x4090ae82},
+               {name:"kvmSetUserMemoryRegion" , got: kvm.IIOW(kvmSetUserMemoryRegion, unsafe.Sizeof(kvm.UserspaceMemoryRegion{})), want: 1075883590},
+               {name:"kvmSetTSSAddr"          , got: kvm.IIO(kvmSetTSSAddr), want: 0xae47},
+               {name:"kvmSetIdentityMapAddr"  , got: kvm.IIOW(kvmSetIdentityMapAddr, 8), want: 0x4008AE48},
+               {name:"kvmCreateIRQChip"       , got: kvm.IIO(kvmCreateIRQChip), want: 0xAE60},
+               {name:"kvmCreatePIT2"          , got: kvm.IIOW(kvmCreatePIT2, unsafe.Sizeof(pitConfig{})), want: 0x4040AE77},
+               {name:"kvmGetSupportedCPUID"   , got: kvm.IIOWR(kvmGetSupportedCPUID, unsafe.Sizeof(kvmCPUID)), want: 0xC008AE05},
+               {name:"kvmSetCPUID2"           , got: kvm.IIOW(kvmSetCPUID2, unsafe.Sizeof(kvmCPUID)), want: 0x4008AE90},
+               {name:"kvmIRQLine"             , got: kvm.IIOW(kvmIRQLine, unsafe.Sizeof(irqLevel{})), want: 0xc008ae67},
+       } {
+               test := test
+               t.Run(test.name, func(t *testing.T) {
+                       if test.got != test.want {
+                               t.Errorf("%s:%d != %d", test.name, test.want, test.got)
+                       }
+               })
+       }
+}

ubuntu2004thinkpad:~/gokvm$ sudo env "PATH=$PATH" go test ./kvm -run TestConst
--- FAIL: TestConst (0.00s)
    --- FAIL: TestConst/kvmIRQLine (0.00s)
        kvm_test.go:472: kvmIRQLine:3221794407 != 1074310753
FAIL
FAIL    github.com/bobuhiro11/gokvm/kvm 0.002s
FAIL
```

**Comment by ChriMarMe** [comment]
The value of kvmIRQLine(0x61) is not correct, because the value used is of kvmIRQLineStatus(0x67).

Also kvmIRQLine is a IOW function, and kvmIRQLineStatus is a IOWR function.

**Comment by ChriMarMe** [comment]
Praise the CI god!

**Review by bobuhiro11 — APPROVED** [review]
Looks good to me.
Thanks so much for the great improvements!!

> Naming of kvmIRQLine was misleading me to believe the value must be 0x61, but the actual > value must be 0x67, which is kvmIRQLineStatus. I adapted the code accordingly

Ohh, sorry for the trouble. Thanks for the correction.

**Pull request merged**
