### PR TITLE
Support multi vcpus

### PR DESCRIPTION
**Pull request by cs8425**
fix #22  `watchdog: BUG: soft lockup - CPU#0 stuck for XXs!`
but still not see more CPU in `/proc/cpuinfo`

### CODE REVIEW

**Comment by bobuhiro11** [comment]
Thank you for your useful contribution!
Sorry, but the test is failing, please check.
https://app.travis-ci.com/github/bobuhiro11/gokvm/builds/237534183

**Comment by cs8425** [comment]
I have no idea why `goveralls -service=travis-ci` got a 405 error...
But other stuffs build without error (include `make test`).

**Comment by bobuhiro11** [comment]
@cs8425 
Thanks for the improvement!
It seems that [coveralls.io](https://coveralls.io/) is under maintenance, which is why it returns a 405 error [1]. The code looks good, so if you delete 400ff917d2c8517e4d94a075150e223477c9a94f and all subsequent commits from this branch, I will merge.
[1] https://github.com/mattn/goveralls/issues/204

**Comment by bobuhiro11** [comment]
@cs8425 I agree with multi-core build. If it is complicated, you can submit another pull request.

**Comment by cs8425** [comment]
ok, thanks for your kind reply.
I remove all commits after d4b06df via force push,
but it seems not trigger a rebuild....

**Review by bobuhiro11 — APPROVED** [review]
LGTM!
Thanks. I've already confirmed that `make test` succeeds in previous builds.

**Pull request merged**
