### PR TITLE
Fixtests

### PR DESCRIPTION
**Pull request by rminnich**
These tests had panics and failures when importing them.

### CODE REVIEW

**Comment by rminnich** [comment]
I'm not able to add reviewers, not sure why

**Comment by rminnich** [comment]
if you're interested I can help convert your CI to github actions, it's a lot easier.

**Comment by rminnich** [comment]
note that golangci-lint specifically recommends you NOT run with --enable-all because of the possibility that, over time, you will break your ci

The makefile is fragile and I can not use it when I import this code base, so the tests I'm adding are essential. In at least one case, failure to check errors and such is leading to a nil pointer deref.

**Comment by bobuhiro11** [comment]
@rminnich 

LGTM!
Thanks for fix and helpful advice.
I can confirm that "make test" passes even with a non-root user.

> if you're interested I can help convert your CI to github actions, it's a lot easier.

As far as I know, with Github Actions, all tests in kvm/kvm_test.go fail because /dev/kvm does not exist. On the other hand, with travis CI, they pass. If Github Actions has any improvements on this, I will consider adopting it.

> golangci-lint specifically recommends you NOT run with --enable-all

I did not notice that. I'll read the documentation and fix it with another PR if necessary.

**Comment by rminnich** [comment]
Thanks!
I am unable to commit, if you can push this is will unblock me :-)

This is a very nice piece of code :-)

**Comment by rminnich** [comment]
Thanks for clearing me up on the github actions issue, that makes a lot of sense!

**Pull request merged**
