### PR TITLE
DON'T MERGE: debug CI

### PR DESCRIPTION
**Pull request by bobuhiro11**

### CODE REVIEW

**Comment by ChriMarMe** [comment]
Maybe TravisCI deactivated kvm nesting?

**Comment by ChriMarMe** [comment]
I saw your twitter post about it. Let me know if I can donate some for the cost of the CI cause I'm using it extensivly and will continue to do so. :)

**Comment by bobuhiro11** [comment]
Travis CI has informed me that it has been resolved.
It seems to have indeed been fixed.

> Let me know if I can donate some for the cost of the CI cause I'm using it extensivly and will continue to do so. :)

Thanks so much!
We are using Travis CI's OSS Plan now (so no cost), but may revisit it in the future.

**Comment by ChriMarMe** [comment]
Ok. As soon as you need some funds, let me know. I'm happy to help :)

**Comment by bobuhiro11** [comment]
Travis CI is back to normal.

**Pull request closed without merging**
