### PR TITLE
Kvmflag

### PR DESCRIPTION
**Pull request by rminnich**

### CODE REVIEW

**Comment by rminnich** [comment]
Any idea why this failed? I don't understand the error message.

**Comment by bobuhiro11** [comment]
Thanks for the improvement.

The following two patches look good.
8eb8359e9ebac024d096ba54d9387d4b8bf0454f
6d284ea24ced57a2b7946704de74cbb30cfed9a6

> main.go:1: : error obtaining VCS status: exit status 128
> Use -buildvcs=false to disable VCS stamping.

As you are already aware, this error seems to occur only in Go 1.18. It also reproduces in the main branch, so please let me investigate this as a separate issue. I will let you know if it is resolved.

**Comment by bobuhiro11** [comment]
This patch https://github.com/bobuhiro11/gokvm/pull/98 fixes the problem with buildvcs. Could you take a look?
I would like to keep Go 1.17 and golangci-lint enabled.

**Comment by bobuhiro11** [comment]
CI for Go 1.18 would be successful.
Could you please rebase this pull request on main branch?

**Comment by rminnich** [comment]
Made the change!

**Review by bobuhiro11 — APPROVED** [review]
Thanks!

**Pull request merged**
